version: '3.8'

services:
  db:
    image: postgres:15
    container_name: finance_db
    restart: always
    environment:
      POSTGRES_DB: finance_manager
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
